### ISSUE TITLE
Builder Fails for Mongooseim 2.0.1 (stable release)

### ISSUE THREAD

**Issue by jonathanve** [esl/mongooseim-docker#11]
When running:

```
$ docker exec -i mongooseim-builder /build.sh MongooseIM https://github.com/esl/MongooseIM 2.0.1

==> rel (generate)
ERROR: Unable to generate spec: read file info /usr/lib/erlang/man/man1/gcov-tool.1.gz failed
ERROR: Unexpected error: rebar_abort
ERROR: generate failed while processing /tmp/mongooseim/rel: rebar_abort
Makefile:101: recipe for target 'rel' failed
make: *** [rel] Error 1
build failed
```

**Comment by jonathanve** [comment]
Hi @michalslaski . Hope you're ok. I've succeeded building an image from master branch, not from 2.0.1 release/tag. Now I can restart my work on this. Do you have any clue on why this is happening? I'll read the code anyway.

Thanks!

**Comment by michalwski** [comment]
From what I remember this is related to the Erlang version installed on builder and reltool used by rebar2 to generate the release. Newer MongooseIM versions use rebar3 and relx to build the release which doesn't try to read the problematic file.

**Comment by jonathanve** [comment]
Thanks @michalwski . I updated erlang version to 19.3.6 in the builder & I got the same error. It is definitely due to rebar2 in 2.0.1. I can see PR #1033 in the beta versions for rebar3.

**Comment by jonathanve** [comment]
@michalwski I was able to generate a tarball for 2.0.1. A builder with phusion/baseimage:0.9.18, esl-erlang=1:17.5.3 and hacking the build script to run tools/configure full instead of tools/configure with-all. I got some errors when running the cluster, missing vm.args and stuff like that, but it is a start.

**Comment by michalwski** [comment]
I see you really want to use MongooseIM 2.0.1 :) Why is that? Do you have some custom modification which are hard to port to current master?

**Comment by jonathanve** [comment]
We do have custom modifications related to groups from 2.0.1

We can port them to current master since given your comment then is stable enough to do it. Was hesitating about that since the latest stable tag was 2.0.1
