### ISSUE TITLE
Docker image broken given no esl-erlang for Ubuntu Xenial

### ISSUE THREAD

**Issue by jonathanve** [esl/mongooseim-docker#2]
```
Get:7 http://packages.erlang-solutions.com/debian xenial/contrib amd64 Packages [49.2 kB]
[...]
E: Version '1:17.5.3' for 'esl-erlang' was not found
```

As shown, the version specified in the Dockerfile does not exist as deb package for ubuntu xenial. Browsing the erl-solutions website, for 17.5.3 the latest one is trusty. So, there are 2 ways to solve this:

1. A esl-erlang:1:17.5.3 deb pkg is created and upload it to xenial repos
2. Rollback phusion/baseimage-docker to a previous version which uses trusty (ie: 0.9.18)

A similar thing happened last time for ppikula's image:
https://github.com/ppikula/mongooseim-docker/commit/87711f4c592bc0a058cbbc6a3fb968a87e83edde

**Comment by michalwski** [comment]
Hi @jonathanve 

Thanks for contacting us. Do you want to build docker image for your customised MongooseIM or the one from upstream? If you are interested in upstream you can download MongooseIM docker image from: https://hub.docker.com/r/mongooseim/mongooseim/

**Comment by jonathanve** [comment]
Thanks @michalwski.  A custom image indeed.

**Comment by michalwski** [comment]
I suggest using newer Erlang, 18.3 or 19.2. This will mean that you will need to modify the Dockerfile.
