### ISSUE TITLE
Checking cluster membership is not correct

### ISSUE THREAD

**Issue by ivanov-aleksander** [esl/mongooseim-docker#31]
I have faced and issue with a cluster with more than 10 nodes. I have created [PR 30 ](https://github.com/esl/mongooseim-docker/pull/30)to fix this issue. 
But I found the second issue:
The [condition](https://github.com/esl/mongooseim-docker/blob/master/member/start.sh#L79) that checks if node already joined the cluster is not correct. 
For example: 
1. Node mongooseim-10 fails to join to cluster because issue  [PR 30 ](https://github.com/esl/mongooseim-docker/pull/30) as result pod will be restarted. But mnesia folder will be created.
2. Next start of the node mongooseim-10 skip joining the cluster because mnesia folder exist. As a result, it will be standalone node.

**Comment by michalwski** [comment]
Thanks for opening the issue. This is indeed a problem, I'll add this to our internal road map.
