### ISSUE TITLE
Issue with second node of mongooseim cluster (docker image)

### ISSUE THREAD

**Issue by sordak** [esl/mongooseim-docker#38]
Hello all

I am trying to deploy cluster with 2 nodes using commands below:

    docker network create mim_cluster

    docker run -d -t --network mim_cluster -h mongooseim-1 --name mongooseim-1 -v `pwd`/mongooseim-dev-official:/usr/lib/mongooseim/etc -p 5222:5222 -p 5280:5280 -p 9100:9100 mongooseim/mongooseim:latest

    docker run -d -t --network mim_cluster -h mongooseim-2 --name mongooseim-2 -v `pwd`/mongooseim-dev-official:/usr/lib/mongooseim/etc mongooseim/mongooseim:latest

It attachment you can see output of:

    docker logs mongooseim-1

    docker logs mongooseim-2

[mongooseim-1.log](https://github.com/esl/mongooseim-docker/files/5084983/node-1.log)
[mongooseim-2.log](https://github.com/esl/mongooseim-docker/files/5084984/node-2.log)

2nd node error messages:

    14:15:11.805 [error] Error in process <0.309.0> on node 'mongooseim@mongooseim-2' with exit value:
    {badarg,[{ets,insert,[mnesia_gvar,{last_error,{{aborted,{node_not_running,'mongooseim@mongooseim-2'}},[{mnesia_loader,wait_on_load_complete,1,[{file,"mnesia_loader.erl"},{line,359}]},{mnesia_tm,apply_fun,3,[{file,"mnesia_tm.erl"},{line,840}]},{mnesia_tm,execute_transaction,5,[{file,"mnesia_tm.erl"},{line,816}]},{mnesia_loader,init_receiver,5,[{file,"mnesia_loader.erl"},{line,285}]},{mnesia_loader,do_get_network_copy,5,[{file,"mnesia_loader.erl"},{line,221}]},{mnesia_controller,'-load_table_fun/1-fun-4-',5,[{file,"mnesia_controller.erl"},{line,2186}]},{mnesia_controller,'-load_and_reply/2-fun-0-',2,[{file,"mnesia_controller.erl"},{line,2133}]}]}}],[]},{mnesia_lib,set,2,[{file,"mnesia_lib.erl"},{line,443}]},{mnesia_lib,fix_error,1,[{file,"mnesia_lib.erl"},{line,906}]},{mnesia_tm,return_abort,3,[{file,"mnesia_tm.erl"},{line,962}]},{mnesia_loader,init_receiver,5,[{file,"mnesia_loader.erl"},{line,285}]},{mnesia_loader,do_get_network_copy,5,[{file,"mnesia_loader.erl"},{line,221}]},{mnesia_controller,'-load_table_fun/1-fun-4-',5,[{file,"mnesia_controller.erl"},{line,2186}]},{mnesia_controller,'-load_and_reply/2-fun-0-',2,[{file,"mnesia_controller.erl"},{line,2133}]}]}
    14:15:11.805 [error] Error in process <0.310.0> on node 'mongooseim@mongooseim-2' with exit value:
    {badarg,[{ets,insert,[mnesia_gvar,{last_error,{{aborted,{node_not_running,'mongooseim@mongooseim-2'}},[{mnesia_loader,wait_on_load_complete,1,[{file,"mnesia_loader.erl"},{line,359}]},{mnesia_tm,apply_fun,3,[{file,"mnesia_tm.erl"},{line,840}]},{mnesia_tm,execute_transaction,5,[{file,"mnesia_tm.erl"},{line,816}]},{mnesia_loader,init_receiver,5,[{file,"mnesia_loader.erl"},{line,285}]},{mnesia_loader,do_get_network_copy,5,[{file,"mnesia_loader.erl"},{line,221}]},{mnesia_controller,'-load_table_fun/1-fun-4-',5,[{file,"mnesia_controller.erl"},{line,2186}]},{mnesia_controller,'-load_and_reply/2-fun-0-',2,[{file,"mnesia_controller.erl"},{line,2133}]}]}}],[]},{mnesia_lib,set,2,[{file,"mnesia_lib.erl"},{line,443}]},{mnesia_lib,fix_error,1,[{file,"mnesia_lib.erl"},{line,906}]},{mnesia_tm,return_abort,3,[{file,"mnesia_tm.erl"},{line,962}]},{mnesia_loader,init_receiver,5,[{file,"mnesia_loader.erl"},{line,285}]},{mnesia_loader,do_get_network_copy,5,[{file,"mnesia_loader.erl"},{line,221}]},{mnesia_controller,'-load_table_fun/1-fun-4-',5,[{file,"mnesia_controller.erl"},{line,2186}]},{mnesia_controller,'-load_and_reply/2-fun-0-',2,[{file,"mnesia_controller.erl"},{line,2133}]}]}
    14:15:11.826 [info] Application mnesia exited with reason: stopped
    14:15:16.055 [info] Checking STUN stun.freeswitch.org
    :0: Warning: export_all flag enabled - all functions will be exported
    14:15:16.211 [info] NkPACKET v0.6.1 has started.
    14:15:16.211 [info] Main IP is 172.19.0.3 (::1). External IP is 28.101.102.87
    14:15:16.248 [info] NkSERVICE vv0.2.0 has started.
    :0: Warning: export_all flag enabled - all functions will be exported
    14:15:16.304 [info] NkSIP v0.5.0 has started

What is wrong?

**Comment by chrzaszcz** [comment]
I know it has been 3 years since this was logged, and I admit we don't often check issues for this repo, as this is a helper repository for MongooseIM. Anyway, I double-checked it now, and the provided commands work correctly in the current version. The reported error messages are related to Mnesia clustering, but they shouldn't prevent the cluster from running. We have the new CETS alternative to Mnesia, which can prevent such issues.
